# Generated by Django 3.1.7 on 2021-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210423_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='smiledos',
            name='video',
            field=models.CharField(default='no video', max_length=100),
        ),
    ]
