# Generated by Django 3.1.7 on 2021-04-23 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_smiledos_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmileDosData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(max_length=100)),
                ('user2', models.CharField(max_length=100)),
                ('video', models.CharField(default='no video', max_length=100)),
                ('smile_dos', models.DecimalField(decimal_places=1, max_digits=4)),
                ('joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='smiledos',
            name='video',
        ),
    ]
