# Generated by Django 3.1.7 on 2021-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('subject', models.CharField(max_length=250, verbose_name='件名')),
                ('contents', models.TextField(verbose_name='お問い合わせ内容')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
            ],
        ),
    ]
